export {
  UK_NATIONS,
  WORKPLACE_SETTINGS,
  GRADE_SUGGESTIONS,
  SPECIALTY_SUGGESTIONS,
  GRADE_PLACEHOLDER,
  SPECIALTY_PLACEHOLDER,
  CLINICAL_PROFILE_HINT,
  MEMORY_FIELD_HINT,
  getMissingProfileFields,
  isProfileIncomplete,
  profileCompletionTitle,
  validateSignupClinicalProfile,
  inferAudienceBand,
  resolveSpecialty,
  formatClinicianSignOff,
  buildClinicianContext,
  buildClinicianPromptBlock,
  signupMetadataFromClinicalProfile,
  isUkNation,
  isWorkplaceSetting,
} from "@umbil/shared";

export type {
  UkNation,
  WorkplaceSetting,
  AudienceBand,
  ClinicianContextInput,
  MissingProfileFields,
} from "@umbil/shared";
