import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica' },
  header: { marginBottom: 30, borderBottomWidth: 1, borderBottomColor: '#1e3a8a', paddingBottom: 10 },
  title: { fontSize: 24, fontWeight: 'bold', color: '#1e3a8a', marginBottom: 5 },
  subtitle: { fontSize: 12, color: '#6b7280' },
  section: { marginBottom: 20 },
  sectionTitle: { fontSize: 16, fontWeight: 'bold', backgroundColor: '#f3f4f6', padding: 8, marginBottom: 10 },
  row: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: '#e5e7eb' },
  label: { fontSize: 11, color: '#374151', width: '70%' },
  value: { fontSize: 11, fontWeight: 'bold', color: '#111827', width: '30%', textAlign: 'right' },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, textAlign: 'center', fontSize: 9, color: '#9ca3af' }
});

interface MsfPdfProps {
  cycleDate: string;
  responseCount: number;
}

export default function MsfPdfDocument({ cycleDate, responseCount }: MsfPdfProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Multi-Source Feedback (MSF) Report</Text>
          <Text style={styles.subtitle}>Generated by Umbil Appraisals</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Cycle Details</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Cycle Date</Text>
            <Text style={styles.value}>{cycleDate}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Responses Gathered</Text>
            <Text style={styles.value}>{responseCount} (Anonymity Threshold Met)</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Status</Text>
            <Text style={styles.value}>Closed & Validated</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Aggregated Domain Scores</Text>
          {/* In a fully connected implementation, you pass the calculated averages here */}
          <View style={styles.row}>
            <Text style={styles.label}>Clinical Assessment</Text>
            <Text style={styles.value}>View Digital Dashboard</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Communication</Text>
            <Text style={styles.value}>View Digital Dashboard</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Teamwork</Text>
            <Text style={styles.value}>View Digital Dashboard</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Professionalism</Text>
            <Text style={styles.value}>View Digital Dashboard</Text>
          </View>
        </View>

        <Text style={styles.footer}>
          This document confirms the completion of an MSF cycle via Umbil. 
          Individual anonymized comments and detailed radar charts are securely stored in the user's digital dashboard.
        </Text>
      </Page>
    </Document>
  );
}