// src/app/terms/page.tsx
"use client";

import Link from "next/link";

export default function TermsPage() {
  return (
    <section className="main-content">
      <div className="container max-w-4xl mx-auto py-12 px-4">
        <div className="mb-8 text-center">
          <h1 className="text-3xl font-bold mb-4">Terms of Use</h1>
          <p className="text-slate-500">Last updated: {new Date().toLocaleDateString('en-GB', { month: 'long', year: 'numeric' })}</p>
        </div>

        <div className="card mb-8">
          <div className="card__body space-y-6">
            
            {/* 1. Acceptance */}
            <section>
              <h2 className="text-xl font-semibold mb-3 text-teal-600">1. Acceptance of Terms</h2>
              <p className="mb-2">
                By accessing or using Umbil ("the Service"), you agree to be bound by these Terms of Use. 
                If you disagree with any part of the terms, you may not access the Service.
              </p>
              <p>
                The Service is owned and operated by Mastering Medicine Ltd.
              </p>
            </section>

            {/* 2. Medical Disclaimer (CRITICAL) */}
            <section className="p-4 bg-red-50/50 border border-red-200 rounded-lg dark:bg-red-900/10 dark:border-red-800">
              <h2 className="text-xl font-bold mb-3 text-red-700 dark:text-red-500">
                2. Medical Disclaimer & AI Limitations
              </h2>
              <ul className="list-disc pl-5 space-y-2 text-sm font-medium">
                <li>
                  <strong>Not a Medical Device:</strong> Umbil is a clinical workflow and learning support tool. It is NOT a medical device and is not intended for use in the diagnosis, cure, mitigation, treatment, or prevention of disease.
                </li>
                <li>
                  <strong>Professional Judgment:</strong> You verify and agree that you are a qualified healthcare professional. You acknowledge that outputs generated by Umbil (including AI-generated summaries, reflections, and plans) may contain errors, hallucinations, or outdated information.
                </li>
                <li>
                  <strong>Final Responsibility:</strong> You remain solely responsible for all clinical decisions and patient care. You must independently verify all outputs (drug dosages, guidelines, scores) against official sources (e.g., BNF, NICE) before clinical application.
                </li>
              </ul>
            </section>

            {/* 3. Acceptable Use & PHI */}
            <section>
              <h2 className="text-xl font-semibold mb-3 text-teal-600">3. Acceptable Use & Data Safety</h2>
              <p className="mb-2">
                You agree to use the Service only for lawful professional purposes.
              </p>
              <p className="font-semibold mt-4 mb-2">Strict Prohibition on Patient Identifiers:</p>
              <ul className="list-disc pl-5 space-y-2 text-sm">
                <li>
                  You must <strong>NOT</strong> input Protected Health Information (PHI) or personally identifiable patient data (e.g., names, NHS numbers, dates of birth, exact addresses) into the Service.
                </li>
                <li>
                  While we employ automated filters to redact inadvertent inputs, deliberately uploading patient data is a material breach of these Terms and may result in immediate account termination.
                </li>
              </ul>
            </section>

            {/* 4. Limitation of Liability */}
            <section>
              <h2 className="text-xl font-semibold mb-3 text-teal-600">4. Limitation of Liability</h2>
              <p className="mb-2">
                To the maximum extent permitted by applicable law, Mastering Medicine Ltd shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, or goodwill.
              </p>
              <p>
                We accept no liability for clinical errors or adverse patient outcomes resulting from the use of, or reliance upon, information generated by the Service.
              </p>
            </section>

            {/* 5. Accounts */}
            <section>
              <h2 className="text-xl font-semibold mb-3 text-teal-600">5. User Accounts</h2>
              <p className="mb-2">
                You are responsible for safeguarding the password that you use to access the Service. You agree not to disclose your password to any third party.
                We reserve the right to suspend or terminate your account if you violate these Terms.
              </p>
            </section>

            {/* 6. Intellectual Property */}
            <section>
              <h2 className="text-xl font-semibold mb-3 text-teal-600">6. Intellectual Property</h2>
              <p className="mb-2">
                The Service and its original content (excluding content provided by you), features, and functionality are and will remain the exclusive property of Mastering Medicine Ltd.
              </p>
            </section>

            {/* 7. Contact */}
            <section>
              <h2 className="text-xl font-semibold mb-3 text-teal-600">7. Contact Us</h2>
              <p>
                If you have any questions about these Terms, please contact us at <a href="mailto:masteringmedicineltd@gmail.com" className="underline hover:text-teal-500">masteringmedicineltd@gmail.com</a>.
              </p>
            </section>

          </div>
        </div>

        <div className="text-center mt-8">
          <Link href="/" className="text-sm font-medium hover:underline opacity-70 hover:opacity-100">
            &larr; Back to Home
          </Link>
        </div>
      </div>
    </section>
  );
}