// src/app/terms/page.tsx
"use client";

import Link from "next/link";

export default function TermsPage() {
  return (
    <section className="main-content">
      <div className="container max-w-4xl mx-auto py-12 px-4">
        <div className="mb-8 text-center">
          <h1 className="text-3xl font-bold mb-4">Terms of Use</h1>
          <p className="text-slate-500">Last updated: February 2026</p>
        </div>

        <div className="card mb-8">
          <div className="card__body space-y-8">
            
            {/* 1. Acceptance */}
            <section>
              <h2 className="text-xl font-semibold mb-3 text-teal-600">1. Acceptance of Terms</h2>
              <p className="mb-2">
                By accessing or using Umbil (“the Service”), you agree to be bound by these Terms of Use. If you do not agree to these Terms, you must not access or use the Service.
              </p>
              <p>
                The Service is owned and operated by Mastering Medicine Ltd (“we”, “us”, or “our”).
              </p>
            </section>

            {/* 2. Eligibility */}
            <section>
              <h2 className="text-xl font-semibold mb-3 text-teal-600">2. Eligibility & Intended Users</h2>
              <ul className="list-disc pl-5 space-y-2 text-sm">
                <li>
                  <strong>Qualified Professionals:</strong> The Service is intended solely for use by qualified healthcare professionals. By using Umbil, you confirm that you hold appropriate professional qualifications and registrations relevant to your role and that you are acting within your professional scope of practice.
                </li>
                <li>
                  <strong>UK Focus:</strong> The Service is designed for use within the United Kingdom. We make no representations that the Service is appropriate or available for use outside the UK.
                </li>
              </ul>
            </section>

            {/* 3. Medical Disclaimer (CRITICAL - Red Box) */}
            <section className="p-5 bg-red-50/50 border border-red-200 rounded-lg dark:bg-red-900/10 dark:border-red-800">
              <h2 className="text-xl font-bold mb-3 text-red-700 dark:text-red-500">
                3. Medical Disclaimer & AI Limitations
              </h2>
              <div className="space-y-4 text-sm font-medium">
                <div>
                  <strong className="block text-red-800 dark:text-red-400 mb-1">Not a Medical Device</strong>
                  <p>Umbil is a clinical workflow and learning support tool. It is not a medical device and is not intended for use in the diagnosis, cure, mitigation, treatment, or prevention of disease.</p>
                </div>
                
                <div>
                  <strong className="block text-red-800 dark:text-red-400 mb-1">Professional Judgment Required</strong>
                  <p>You acknowledge that outputs generated by the Service (including AI-generated summaries, reflections, plans, letters, or suggestions) may contain errors, omissions, hallucinations, or outdated information.</p>
                </div>

                <div>
                  <strong className="block text-red-800 dark:text-red-400 mb-1">Final Responsibility</strong>
                  <p>You remain solely responsible for all clinical decisions and patient care. You must independently verify all outputs (including drug dosages, guidelines, scores, or recommendations) against authoritative sources (e.g. BNF, NICE, SIGN) before any clinical application.</p>
                </div>

                <div>
                  <strong className="block text-red-800 dark:text-red-400 mb-1">No Emergency Use</strong>
                  <p>The Service is not intended for use in medical emergencies or time-critical clinical situations. Do not rely on the Service where immediate clinical decision-making is required.</p>
                </div>
              </div>
            </section>

            {/* 4. Acceptable Use & Data Safety (Amber Box) */}
            <section className="p-5 bg-amber-50/50 border border-amber-200 rounded-lg dark:bg-amber-900/10 dark:border-amber-800">
              <h2 className="text-xl font-bold mb-3 text-amber-700 dark:text-amber-500">
                4. Acceptable Use & Data Safety
              </h2>
              <p className="mb-3 text-sm">You agree to use the Service only for lawful, professional, and ethical purposes.</p>
              
              <strong className="block mb-2 text-amber-800 dark:text-amber-400">Strict Prohibition on Patient Identifiers</strong>
              <p className="mb-2 text-sm">
                You must not input Protected Health Information (PHI) or personally identifiable patient data into the Service, including but not limited to:
              </p>
              <ul className="list-disc pl-5 mb-3 text-sm space-y-1">
                <li>Patient names</li>
                <li>NHS numbers</li>
                <li>Dates of birth</li>
                <li>Exact addresses</li>
                <li>Any other information that could identify an individual patient</li>
              </ul>
              <p className="text-sm">
                While we employ automated filters to detect and redact inadvertent identifiers, you remain fully responsible for ensuring that all content you submit is anonymised at the source. 
                Deliberately uploading patient-identifiable data constitutes a material breach of these Terms.
              </p>
            </section>

            {/* 5. User Accounts */}
            <section>
              <h2 className="text-xl font-semibold mb-3 text-teal-600">5. User Accounts</h2>
              <p className="mb-2">
                You are responsible for safeguarding the credentials used to access the Service and for all activity carried out under your account.
                You agree not to share your login details with any third party. We reserve the right to suspend or terminate your account if you breach these Terms or misuse the Service.
              </p>
            </section>

            {/* 6. Service Availability */}
            <section>
              <h2 className="text-xl font-semibold mb-3 text-teal-600">6. Service Availability</h2>
              <p className="mb-2">
                We do not guarantee that the Service will be available at all times, uninterrupted, secure, or error-free.
                We may suspend, withdraw, modify, or update the Service (or any part of it) without notice for maintenance, improvements, security, or operational reasons.
              </p>
            </section>

            {/* 7. Intellectual Property */}
            <section>
              <h2 className="text-xl font-semibold mb-3 text-teal-600">7. Intellectual Property</h2>
              <ul className="list-disc pl-5 space-y-2">
                <li>
                  <strong>Our Content:</strong> The Service and its original content (excluding content submitted by users), features, and functionality are and will remain the exclusive property of Mastering Medicine Ltd.
                </li>
                <li>
                  <strong>User Content:</strong> You retain ownership of any content you submit to the Service. By using Umbil, you grant Mastering Medicine Ltd a limited, non-exclusive, royalty-free licence to process such content solely for the purpose of providing and improving the Service, in accordance with our Privacy Policy.
                </li>
              </ul>
            </section>

            {/* 8. Limitation of Liability */}
            <section>
              <h2 className="text-xl font-semibold mb-3 text-teal-600">8. Limitation of Liability</h2>
              <p className="mb-2">
                To the maximum extent permitted by applicable law, Mastering Medicine Ltd shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, or goodwill.
              </p>
              <p>
                To the extent permitted by law, we accept no liability for clinical errors or adverse patient outcomes resulting from the use of, or reliance upon, information generated by the Service.
              </p>
            </section>

            {/* 9. Indemnity */}
            <section>
              <h2 className="text-xl font-semibold mb-3 text-teal-600">9. Indemnity</h2>
              <p className="mb-2">
                You agree to indemnify and hold harmless Mastering Medicine Ltd from and against any claims, damages, losses, liabilities, costs, or expenses arising out of:
              </p>
              <ul className="list-disc pl-5 space-y-1 text-sm">
                <li>Your misuse of the Service</li>
                <li>Your breach of these Terms</li>
                <li>Your failure to comply with applicable laws, regulations, or professional obligations</li>
              </ul>
            </section>

            {/* 10. Changes */}
            <section>
              <h2 className="text-xl font-semibold mb-3 text-teal-600">10. Changes to These Terms</h2>
              <p>
                We may update these Terms from time to time. Continued use of the Service after any changes take effect constitutes acceptance of the revised Terms.
              </p>
            </section>

            {/* 11. Governing Law */}
            <section>
              <h2 className="text-xl font-semibold mb-3 text-teal-600">11. Governing Law & Jurisdiction</h2>
              <p>
                These Terms are governed by and construed in accordance with the laws of England and Wales.
                Any disputes arising out of or in connection with these Terms or the Service shall be subject to the exclusive jurisdiction of the courts of England and Wales.
              </p>
            </section>

            {/* 12. Contact */}
            <section>
              <h2 className="text-xl font-semibold mb-3 text-teal-600">12. Contact Us</h2>
              <p>
                If you have any questions about these Terms, please contact us at: <a href="mailto:masteringmedicineltd@gmail.com" className="underline hover:text-teal-500">masteringmedicineltd@gmail.com</a>
              </p>
            </section>

          </div>
        </div>

        <div className="text-center mt-8">
          <Link href="/" className="text-sm font-medium hover:underline opacity-70 hover:opacity-100">
            &larr; Back to Home
          </Link>
        </div>
      </div>
    </section>
  );
}