import { Ionicons } from "@expo/vector-icons";
import * as Clipboard from "expo-clipboard";
import * as FileSystem from "expo-file-system/legacy";
import { Stack, router, useLocalSearchParams } from "expo-router";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { useEffect, useMemo, useRef, useState } from "react";
import {
  ActivityIndicator,
  Alert,
  Image,
  Linking,
  Modal,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  useWindowDimensions,
  View,
} from "react-native";
import WebView from "react-native-webview";

import {
  CategoryBreakdown,
  DomainBarChart,
  DomainLegend,
} from "@/components/appraisals/AppraisalCharts";
import { streamReflection } from "@/lib/api";
import { getPublicEnv } from "@/lib/env";
import { calculateAnalytics, type AnalyticsResult, type SurveyData } from "@/lib/psqAnalytics";
import { getMyProfile } from "@/lib/profile";
import {
  getPsqSurvey,
  updatePsqCustomQuestions,
  updatePsqExecutiveSummary,
  type PsqSurveyWithResponses,
} from "@/lib/store/appraisals";
import { addCPD } from "@/lib/store/cpd";
import { useTheme } from "@/providers/ThemeProvider";
import { radii, spacing, type ColorPalette } from "@/theme/colors";
import { fonts } from "@/theme/typography";

const isLimitReached = (message: string): boolean =>
  message === "LIMIT_REACHED" || message.includes("LIMIT_REACHED");

const formatDomainName = (name: string) => name.replace(/^Domain \d+: /, "");

const buildPsqReportHtml = (
  survey: PsqSurveyWithResponses,
  analytics: AnalyticsResult,
  executiveSummary: string,
  reflection: string
) => {
  const escape = (value: string) =>
    value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

  const scoresRows = analytics.breakdown
    .map((q) => {
      const scoreDisplay = typeof q.score === "number" ? q.score.toFixed(2) : q.score;
      return `<tr><td>${escape(q.name)}</td><td style="text-align:right;font-weight:700;color:#1fb8cd;">${scoreDisplay}</td></tr>`;
    })
    .join("");

  const appointmentRows =
    analytics.appointmentTypes.length > 0
      ? analytics.appointmentTypes
          .map((t) => `<tr><td>${escape(t.name)}</td><td style="text-align:right;">${t.value}</td></tr>`)
          .join("")
      : `<tr><td colspan="2" style="color:#94a3b8;font-style:italic;text-align:center;">No data recorded</td></tr>`;

  const comment = (label: string, value: string) =>
    value ? `<div class="feedback-card"><strong>${label}:</strong> "${escape(value)}"</div>` : "";

  const commentsHtml = analytics.textFeedback
    .map((fb) => comment("Done well", fb.good) + comment("Improve", fb.improve))
    .join("");

  const customHtml = analytics.customFeedback
    .map(
      (cf) =>
        `<div class="comment-section"><h4>Q: ${escape(cf.question)}</h4><ul>${cf.answers
          .map((a) => `<li>"${escape(a)}"</li>`)
          .join("")}</ul></div>`
    )
    .join("");

  return `
    <html>
      <head>
        <meta charset="utf-8" />
        <style>
          body { font-family: -apple-system, Helvetica, Arial, sans-serif; padding: 32px; color: #1e293b; }
          h1 { color: #0f172a; font-size: 22px; margin-bottom: 4px; }
          .subtitle { color: #64748b; font-size: 13px; margin-bottom: 24px; }
          .summary-box { background: #f0f9ff; border-left: 4px solid #3b82f6; padding: 12px; margin-bottom: 20px; font-size: 13px; color: #1e3a8a; border-radius: 0 8px 8px 0; }
          .dashboard { display: flex; gap: 16px; margin-bottom: 24px; }
          .stat { flex: 1; text-align: center; background: #f0fdfa; border: 1px solid #ccfbf1; border-radius: 10px; padding: 14px; }
          .stat-val { display: block; font-size: 20px; font-weight: 800; color: #1fb8cd; }
          .stat-label { font-size: 10px; color: #115e59; text-transform: uppercase; font-weight: 700; }
          table { width: 100%; border-collapse: collapse; font-size: 13px; margin-bottom: 20px; }
          th, td { border-bottom: 1px solid #e2e8f0; padding: 8px; text-align: left; }
          .section-title { font-size: 14px; font-weight: 700; color: #0f172a; margin: 20px 0 10px; border-left: 3px solid #1fb8cd; padding-left: 8px; }
          .feedback-card { background: #f1f5f9; border-left: 3px solid #cbd5e1; padding: 10px 12px; margin-bottom: 8px; border-radius: 6px; font-size: 12px; }
          .comment-section { margin-bottom: 16px; }
          .reflection-box { background: #fff7ed; border: 1px solid #fed7aa; padding: 16px; border-radius: 8px; white-space: pre-wrap; font-size: 13px; }
        </style>
      </head>
      <body>
        <h1>${escape(survey.title || "PSQ Cycle")}</h1>
        <div class="subtitle">Patient Satisfaction Questionnaire Report &bull; Generated by Umbil</div>
        ${executiveSummary ? `<div class="summary-box"><strong>Appraisal-Ready Summary:</strong> ${escape(executiveSummary)}</div>` : ""}
        <div class="dashboard">
          <div class="stat"><span class="stat-val">${analytics.stats.totalResponses}</span><span class="stat-label">Total Responses</span></div>
          <div class="stat"><span class="stat-val">${analytics.stats.averageScore}</span><span class="stat-label">Average Score</span></div>
          <div class="stat"><span class="stat-val" style="font-size:14px;">${escape(formatDomainName(analytics.stats.topArea))}</span><span class="stat-label">Top Area</span></div>
        </div>
        <div class="section-title">Score Breakdown</div>
        <table>${scoresRows}</table>
        <div class="section-title">Consultations</div>
        <table>${appointmentRows}</table>
        ${reflection ? `<div class="section-title">Reflection & Action Plan</div><div class="reflection-box">${escape(reflection)}</div>` : ""}
        ${commentsHtml ? `<div class="section-title">Patient Comments</div>${commentsHtml}` : ""}
        ${customHtml ? `<div class="section-title">Practice-Specific Questions</div>${customHtml}` : ""}
      </body>
    </html>
  `;
};

const PsqDetailScreen = () => {
  const { colors } = useTheme();
  const { width } = useWindowDimensions();
  const { id } = useLocalSearchParams<{ id: string }>();
  const [survey, setSurvey] = useState<PsqSurveyWithResponses | null>(null);
  const [loading, setLoading] = useState(true);
  const [customQuestions, setCustomQuestions] = useState<string[]>([]);
  const [saving, setSaving] = useState(false);
  const [copied, setCopied] = useState(false);
  const [savingQr, setSavingQr] = useState(false);
  const [kioskVisible, setKioskVisible] = useState(false);
  const [kioskLoading, setKioskLoading] = useState(true);
  const webviewRef = useRef<WebView>(null);
  const { apiUrl } = getPublicEnv();
  const origin = apiUrl.replace(/\/$/, "") || "https://umbil.ai";
  const shareUrl = `${origin}/s/${id}`;
  const kioskUrl = `${shareUrl}?kiosk=true`;
  const qrImageUrl = `https://api.qrserver.com/v1/create-qr-code/?size=180x180&data=${encodeURIComponent(
    shareUrl
  )}`;

  const [isPro, setIsPro] = useState(false);
  const [profileLoading, setProfileLoading] = useState(true);

  const [executiveSummary, setExecutiveSummary] = useState("");
  const [isGeneratingSummary, setIsGeneratingSummary] = useState(false);
  const hasGeneratedSummary = useRef(false);

  const [reflection, setReflection] = useState("");
  const [isGeneratingReflection, setIsGeneratingReflection] = useState(false);
  const [copiedReflection, setCopiedReflection] = useState(false);
  const [savingLog, setSavingLog] = useState(false);
  const [exportingPdf, setExportingPdf] = useState(false);

  useEffect(() => {
    void getPsqSurvey(id).then(({ data }) => {
      setSurvey(data);
      setCustomQuestions(data?.custom_questions || []);
      setExecutiveSummary(data?.executive_summary || "");
      setLoading(false);
    });
    void getMyProfile()
      .then((p) => setIsPro(!!p?.is_pro || p?.subscription_status === "active"))
      .finally(() => setProfileLoading(false));
  }, [id]);

  const analytics: AnalyticsResult | null = useMemo(() => {
    if (!survey) return null;
    return calculateAnalytics([survey as unknown as SurveyData]);
  }, [survey]);

  const responses = analytics?.stats.totalResponses ?? survey?.psq_responses?.length ?? 0;
  const required = analytics?.stats.targetThreshold ?? survey?.required_responses ?? 34;
  const isThresholdMet = analytics?.stats.thresholdMet ?? false;
  const progress = Math.min(100, (responses / required) * 100);
  const chartWidth = Math.min(width - spacing.lg * 2 - spacing.lg * 2, 360);

  const goodComments = analytics?.textFeedback.filter((fb) => fb.good) ?? [];
  const improveComments = analytics?.textFeedback.filter((fb) => fb.improve) ?? [];
  const hasComments = goodComments.length > 0 || improveComments.length > 0;

  const generateExecutiveSummary = async (statsData: AnalyticsResult) => {
    if (survey?.executive_summary) {
      setExecutiveSummary(survey.executive_summary);
      return;
    }

    setIsGeneratingSummary(true);
    try {
      let fullSummary = "";
      await streamReflection({
        body: {
          mode: "executive_summary",
          stats: statsData.stats,
          strengths: statsData.stats.topArea,
          weaknesses: statsData.stats.lowestArea,
          comments: statsData.textFeedback.slice(0, 5).map((t) => t.good || t.improve).filter(Boolean),
        },
        onChunk: (text) => {
          fullSummary += text;
          setExecutiveSummary((prev) => prev + text);
        },
      });

      await updatePsqExecutiveSummary(id, fullSummary);
    } catch {
      setExecutiveSummary("Unable to generate automatic summary at this time. Please review the detailed metrics below.");
    } finally {
      setIsGeneratingSummary(false);
    }
  };

  useEffect(() => {
    if (isThresholdMet && isPro && analytics && !hasGeneratedSummary.current) {
      hasGeneratedSummary.current = true;
      void generateExecutiveSummary(analytics);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [analytics, isPro, isThresholdMet]);

  const handleGenerateReflection = async () => {
    if (!analytics) return;
    setIsGeneratingReflection(true);
    setReflection("");
    try {
      await streamReflection({
        body: {
          mode: "psq_analysis",
          stats: analytics.stats,
          strengths: analytics.stats.topArea,
          weaknesses: analytics.stats.lowestArea,
          comments: analytics.textFeedback.slice(0, 5).map((t) => t.good || t.improve).filter(Boolean),
        },
        onChunk: (text) => {
          setReflection((prev) => prev + text);
        },
      });
    } catch (err) {
      Alert.alert(
        "AI failed",
        err instanceof Error ? err.message : "Failed to generate reflection. Please try again."
      );
    } finally {
      setIsGeneratingReflection(false);
    }
  };

  const copyReflection = async () => {
    if (!reflection) return;
    await Clipboard.setStringAsync(reflection);
    setCopiedReflection(true);
    setTimeout(() => setCopiedReflection(false), 2000);
  };

  const handleSaveToLog = async () => {
    if (!reflection.trim() || !analytics || !survey) return;
    setSavingLog(true);
    try {
      const { error } = await addCPD({
        timestamp: new Date().toISOString(),
        question: `Patient Satisfaction Questionnaire (PSQ) Review - ${survey.title || "PSQ Cycle"}`,
        answer:
          executiveSummary ||
          `Reviewed feedback from ${analytics.stats.totalResponses} patients. Overall score: ${analytics.stats.averageScore}/5.0.`,
        reflection: reflection.trim(),
        tags: ["PSQ", "Patient Feedback", "Appraisal", "Domain 3", "Domain 4"],
        duration: 30,
      });

      if (error) {
        if (isLimitReached(error.message || "")) {
          Alert.alert(
            "Upgrade to Pro",
            "You have reached your monthly CPD logging limit. Please upgrade to Pro.",
            [
              { text: "Not now", style: "cancel" },
              { text: "Upgrade", onPress: () => router.push("/(app)/pro") },
            ]
          );
        } else {
          Alert.alert("Save failed", error.message || "Could not save to Capture learning. Please try again.");
        }
        return;
      }
      Alert.alert("Saved", "Saved to Capture learning successfully!");
    } finally {
      setSavingLog(false);
    }
  };

  const exportPdf = async () => {
    if (!survey || !analytics) return;
    setExportingPdf(true);
    try {
      const html = buildPsqReportHtml(survey, analytics, executiveSummary, reflection);
      const { uri } = await Print.printToFileAsync({ html });
      const canShare = await Sharing.isAvailableAsync();
      if (canShare) {
        await Sharing.shareAsync(uri, {
          mimeType: "application/pdf",
          dialogTitle: "Share PSQ report",
        });
      } else {
        Alert.alert("Export ready", "PDF generated but sharing is unavailable on this device.");
      }
    } catch (err) {
      Alert.alert(
        "Export failed",
        err instanceof Error ? err.message : "Could not generate the PDF report."
      );
    } finally {
      setExportingPdf(false);
    }
  };

  const persistQuestions = async (updated: string[]) => {
    setSaving(true);
    setCustomQuestions(updated);
    const { error } = await updatePsqCustomQuestions(
      id,
      updated.map((q) => q.trim()).filter(Boolean)
    );
    setSaving(false);
    if (error) {
      Alert.alert("Error", error.message);
      return;
    }
    setSurvey((s) =>
      s
        ? {
            ...s,
            custom_questions: updated.map((q) => q.trim()).filter(Boolean),
          }
        : s
    );
  };

  const addCustomQuestion = () => {
    if (customQuestions.length >= 2) return;
    void persistQuestions([...customQuestions, ""]);
  };

  const updateCustomQuestion = (idx: number, val: string) => {
    const updated = [...customQuestions];
    updated[idx] = val;
    setCustomQuestions(updated);
  };

  const commitCustomQuestions = () => {
    void persistQuestions(customQuestions);
  };

  const removeCustomQuestion = (idx: number) => {
    void persistQuestions(customQuestions.filter((_, i) => i !== idx));
  };

  const copyLink = async () => {
    await Clipboard.setStringAsync(shareUrl);
    setCopied(true);
    Alert.alert("Copied", "Share link copied to clipboard.");
    setTimeout(() => setCopied(false), 2000);
  };

  const shareQrCode = async () => {
    setSavingQr(true);
    try {
      const downloadUrl = `https://api.qrserver.com/v1/create-qr-code/?size=600x600&data=${encodeURIComponent(
        shareUrl
      )}`;
      const fileUri = `${FileSystem.cacheDirectory}psq-qr-${id}.png`;
      const { uri } = await FileSystem.downloadAsync(downloadUrl, fileUri);
      const canShare = await Sharing.isAvailableAsync();
      if (!canShare) {
        Alert.alert(
          "Sharing unavailable",
          "Sharing is not supported on this device."
        );
        return;
      }
      await Sharing.shareAsync(uri, {
        mimeType: "image/png",
        dialogTitle: "Share PSQ QR code",
      });
    } catch (err) {
      Alert.alert(
        "Error",
        err instanceof Error
          ? err.message
          : "Failed to save the QR code. Please try again."
      );
    } finally {
      setSavingQr(false);
    }
  };

  const launchKiosk = () => {
    setKioskLoading(true);
    setKioskVisible(true);
  };

  const confirmExitKiosk = () => {
    Alert.alert(
      "Exit Kiosk Mode?",
      "Only exit once you have taken the device back from the patient.",
      [
        { text: "Cancel", style: "cancel" },
        {
          text: "Exit Kiosk",
          style: "destructive",
          onPress: () => setKioskVisible(false),
        },
      ]
    );
  };

  const styles = makeStyles(colors);

  return (
    <>
      <Stack.Screen
        options={{
          title: "PSQ cycle",
          headerTintColor: colors.primary,
          headerStyle: { backgroundColor: colors.background },
          headerShadowVisible: false,
          headerTitleStyle: { fontFamily: fonts.semiBold, color: colors.text },
        }}
      />
      {loading ? (
        <ActivityIndicator color={colors.primary} style={{ marginTop: 32 }} />
      ) : !survey ? (
        <Text style={styles.empty}>Cycle not found.</Text>
      ) : (
        <ScrollView contentContainerStyle={styles.content}>
          <Text style={styles.title}>{survey.title || "PSQ Cycle"}</Text>
          <Text style={styles.meta}>
            {new Date(survey.created_at).toLocaleDateString()}
          </Text>

          <Text style={styles.heading}>Share Survey</Text>
          <View style={styles.card}>
            <Text style={styles.cardHeading}>Share via Link</Text>
            <Text style={styles.cardHint}>
              Use this for SMS or Email campaigns.
            </Text>
            <Text style={styles.url} selectable>
              {shareUrl}
            </Text>
            <Pressable onPress={() => void copyLink()}>
              <Text style={styles.link}>{copied ? "Copied" : "Copy"}</Text>
            </Pressable>
            <Pressable onPress={() => void Linking.openURL(shareUrl)}>
              <Text style={styles.link}>View Live Survey</Text>
            </Pressable>
          </View>

          <View style={[styles.card, styles.kioskCard]}>
            <View style={styles.kioskCardRow}>
              <View style={styles.kioskIconCircle}>
                <Ionicons
                  name="tablet-portrait-outline"
                  size={22}
                  color={colors.primary}
                />
              </View>
              <View style={styles.kioskCardText}>
                <Text style={styles.cardHeading}>Kiosk Mode</Text>
                <Text style={styles.cardHint}>
                  Auto-refreshes for the next patient.
                </Text>
              </View>
            </View>
            <Pressable style={styles.outlineBtn} onPress={launchKiosk}>
              <Ionicons
                name="play-outline"
                size={16}
                color={colors.primary}
              />
              <Text style={styles.outlineBtnText}>Launch Kiosk</Text>
            </Pressable>
          </View>

          <View style={styles.card}>
            <Text style={styles.cardHeading}>Progress Tracking</Text>
            <View style={styles.progressRow}>
              <Text style={styles.progressCount}>{responses}</Text>
              <Text style={styles.meta}>Target: {required}</Text>
            </View>
            <View style={styles.progressTrack}>
              <View
                style={[
                  styles.progressFill,
                  {
                    width: `${progress}%`,
                    backgroundColor: isThresholdMet
                      ? colors.success
                      : colors.primary,
                  },
                ]}
              />
            </View>
            {isThresholdMet ? (
              <View style={[styles.statusBox, styles.statusOk]}>
                <Text style={[styles.statusTitle, { color: colors.success }]}>
                  Anonymity Threshold Met!
                </Text>
                <Text style={styles.statusBody}>
                  You have enough responses to safely view the aggregated data.
                </Text>
              </View>
            ) : (
              <View style={[styles.statusBox, styles.statusLocked]}>
                <Text style={styles.statusTitle}>Results are Locked</Text>
                <Text style={styles.statusBody}>
                  Results cannot be viewed until {required} responses are
                  reached.
                </Text>
              </View>
            )}
          </View>

          <View style={[styles.card, styles.qrCard]}>
            <View style={styles.qrCaptionRow}>
              <Ionicons
                name="qr-code-outline"
                size={18}
                color={colors.text}
              />
              <Text style={styles.cardHeading}>Scan to Start</Text>
            </View>
            <View style={styles.qrImageWrap}>
              <Image
                source={{ uri: qrImageUrl }}
                style={styles.qrImage}
                accessibilityLabel="QR code linking to the patient survey"
              />
            </View>
            <Text style={styles.qrHint}>
              Print this and place it in your waiting room.
            </Text>
            <Pressable
              style={[styles.outlineBtn, savingQr && styles.btnDisabled]}
              onPress={() => void shareQrCode()}
              disabled={savingQr}
            >
              <Ionicons
                name="share-outline"
                size={16}
                color={colors.primary}
              />
              <Text style={styles.outlineBtnText}>
                {savingQr ? "Preparing…" : "Save / Share QR"}
              </Text>
            </Pressable>
          </View>

          <Text style={styles.heading}>Survey Preview & Configuration</Text>
          <View style={styles.card}>
            <Text style={styles.label}>Core Questions</Text>
            <Text style={styles.cardHint}>
              The 13 core questions are fixed to ensure GMC compliance.
            </Text>
            <View style={styles.standardBadge}>
              <Text style={styles.standardBadgeText}>
                Standardised Set Active
              </Text>
            </View>
          </View>

          <View style={styles.card}>
            <Text style={styles.label}>Custom Questions</Text>
            <Text style={styles.cardHint}>
              Add up to 2 optional questions specific to your practice.
            </Text>
            {customQuestions.map((q, i) => (
              <View key={`cq-${i}`} style={styles.questionRow}>
                <TextInput
                  style={[styles.input, { flex: 1 }]}
                  value={q}
                  onChangeText={(val) => updateCustomQuestion(i, val)}
                  onBlur={commitCustomQuestions}
                  placeholder="e.g. How was the waiting room?"
                  placeholderTextColor={colors.textMuted}
                />
                <Pressable onPress={() => removeCustomQuestion(i)}>
                  <Text style={styles.danger}>Remove</Text>
                </Pressable>
              </View>
            ))}
            {customQuestions.length < 2 ? (
              <Pressable style={styles.dashedBtn} onPress={addCustomQuestion}>
                <Text style={styles.dashedBtnText}>Add Question</Text>
              </Pressable>
            ) : null}
            {saving ? <Text style={styles.saving}>Saving…</Text> : null}
          </View>

          <Text style={styles.heading}>Results & Reflection</Text>

          {!isThresholdMet ? (
            <View style={[styles.card, styles.lockedCard]}>
              <Text style={styles.lockedTitle}>Results & Reflection Locked</Text>
              <Text style={styles.cardHint}>
                To protect anonymity and ensure statistical validity, results
                are hidden until you receive {required} responses.
              </Text>
              <Text style={styles.lockedCount}>
                {responses} / {required} Responses
              </Text>
            </View>
          ) : profileLoading ? (
            <ActivityIndicator color={colors.primary} style={{ marginVertical: spacing.md }} />
          ) : !isPro ? (
            <View style={[styles.card, styles.upsellCard]}>
              <Text style={styles.cardHeading}>Unlock Your Patient Feedback Report</Text>
              <Text style={styles.cardHint}>
                Your {responses} anonymous responses have been securely
                collated. Upgrade to Umbil Pro to unlock the AI
                interpretation, thematic analysis, and appraisal-ready
                exports.
              </Text>
              <Pressable
                style={styles.btn}
                onPress={() => router.push("/(app)/pro")}
              >
                <Text style={styles.btnText}>View Pro Plans</Text>
              </Pressable>
            </View>
          ) : analytics ? (
            <>
              <View style={styles.card}>
                <Text style={styles.cardHeading}>Appraisal-Ready Summary</Text>
                {isGeneratingSummary && !executiveSummary ? (
                  <Text style={styles.cardHintPulsing}>
                    Analyzing responses to generate a summary…
                  </Text>
                ) : (
                  <Text style={styles.summaryBody}>{executiveSummary}</Text>
                )}
              </View>

              <View style={styles.card}>
                <Text style={styles.cardHeading}>Overview</Text>
                <View style={styles.statRow}>
                  <View style={styles.statTile}>
                    <Text style={styles.statValue}>{analytics.stats.totalResponses}</Text>
                    <Text style={styles.statLabel}>Patients</Text>
                  </View>
                  <View style={styles.statTile}>
                    <Text style={styles.statValue}>{analytics.stats.averageScore}</Text>
                    <Text style={styles.statLabel}>/ 5.0 Overall</Text>
                  </View>
                  <View style={styles.statTile}>
                    <Text style={[styles.statValue, styles.statValueText]} numberOfLines={2}>
                      {formatDomainName(analytics.stats.topArea)}
                    </Text>
                    <Text style={styles.statLabel}>Key strength</Text>
                  </View>
                </View>
              </View>

              <View style={styles.card}>
                <View style={styles.cardHeadingRow}>
                  <Text style={styles.cardHeading}>Breakdown by Area</Text>
                  <Pressable
                    style={[styles.outlineBtnSm, exportingPdf && { opacity: 0.6 }]}
                    onPress={() => void exportPdf()}
                    disabled={exportingPdf}
                  >
                    <Text style={styles.outlineBtnSmText}>
                      {exportingPdf ? "Exporting…" : "Export PDF"}
                    </Text>
                  </Pressable>
                </View>
                <Text style={styles.cardHint}>
                  The dotted line marks the standard GMC appraisal target score (4.0).
                </Text>
                {analytics.breakdown.length > 0 ? (
                  <>
                    <DomainBarChart data={analytics.breakdown} width={chartWidth} />
                    <DomainLegend data={analytics.breakdown} />
                  </>
                ) : (
                  <Text style={styles.cardHint}>No data available yet.</Text>
                )}
              </View>

              {analytics.appointmentTypes.length > 0 ? (
                <View style={styles.card}>
                  <Text style={styles.cardHeading}>Consultation Type</Text>
                  <CategoryBreakdown data={analytics.appointmentTypes} />
                </View>
              ) : null}

              {hasComments ? (
                <View style={styles.card}>
                  <Text style={styles.cardHeading}>Patient Comments</Text>
                  <Text style={styles.cardHint}>Displayed randomly to protect anonymity.</Text>

                  <Text style={styles.subLabel}>Done Well</Text>
                  {goodComments.length > 0 ? (
                    goodComments.map((fb, idx) => (
                      <View key={`good-${idx}`} style={styles.commentBlockGood}>
                        <Text style={styles.commentText}>"{fb.good}"</Text>
                      </View>
                    ))
                  ) : (
                    <Text style={styles.emptyComment}>No comments in this category.</Text>
                  )}

                  <Text style={styles.subLabel}>Areas for Improvement</Text>
                  {improveComments.length > 0 ? (
                    improveComments.map((fb, idx) => (
                      <View key={`improve-${idx}`} style={styles.commentBlockImprove}>
                        <Text style={styles.commentText}>"{fb.improve}"</Text>
                      </View>
                    ))
                  ) : (
                    <Text style={styles.emptyComment}>No comments in this category.</Text>
                  )}
                </View>
              ) : null}

              {analytics.customFeedback.length > 0 ? (
                <View style={styles.card}>
                  <Text style={styles.cardHeading}>Practice-Specific Feedback</Text>
                  {analytics.customFeedback.map((cf, idx) => (
                    <View key={`${cf.question}-${idx}`} style={styles.feedbackBlock}>
                      <Text style={styles.feedbackQuestion}>Q: {cf.question}</Text>
                      {cf.answers.map((ans, i) => (
                        <Text key={i} style={styles.feedbackAnswer}>
                          "{ans}"
                        </Text>
                      ))}
                    </View>
                  ))}
                </View>
              ) : null}

              <View style={styles.card}>
                <Text style={styles.cardHeading}>Appraisal-Ready Reflection</Text>
                <Text style={styles.cardHint}>
                  Write your personal reflection below, or tap Auto-Draft to
                  generate insights from this cycle's feedback.
                </Text>
                <Pressable
                  style={[styles.outlineBtnFull, isGeneratingReflection && { opacity: 0.6 }]}
                  onPress={() => void handleGenerateReflection()}
                  disabled={isGeneratingReflection}
                >
                  {isGeneratingReflection ? (
                    <ActivityIndicator color={colors.primary} />
                  ) : (
                    <Text style={styles.outlineBtnFullText}>
                      {reflection ? "Regenerate Auto-Draft" : "Auto-Draft"}
                    </Text>
                  )}
                </Pressable>

                {isGeneratingReflection && !reflection ? (
                  <View style={styles.aiLoading}>
                    <ActivityIndicator color={colors.primary} />
                    <Text style={styles.cardHint}>
                      Umbil AI is drafting your GMC-compliant reflection…
                    </Text>
                  </View>
                ) : null}

                <TextInput
                  style={styles.reflectionInput}
                  multiline
                  textAlignVertical="top"
                  value={reflection}
                  onChangeText={setReflection}
                  placeholder="Tap Auto-Draft to generate insights, or write your own reflection here…"
                  placeholderTextColor={colors.textMuted}
                />

                <View style={styles.reflectionActions}>
                  <Pressable onPress={() => void copyReflection()} disabled={!reflection}>
                    <Text style={[styles.link, !reflection && styles.disabledLink]}>
                      {copiedReflection ? "Copied" : "Copy Text"}
                    </Text>
                  </Pressable>
                  <Pressable
                    style={[
                      styles.btn,
                      (savingLog || !reflection.trim()) && { opacity: 0.6 },
                    ]}
                    onPress={() => void handleSaveToLog()}
                    disabled={savingLog || !reflection.trim()}
                  >
                    <Text style={styles.btnText}>
                      {savingLog ? "Saving…" : "Save to Capture learning"}
                    </Text>
                  </Pressable>
                </View>
              </View>
            </>
          ) : null}

          <Text style={styles.note}>
            Respondents complete the survey on the web. Open the full results
            view on the website for charts and appraisal export.
          </Text>
          <Pressable
            onPress={() => void Linking.openURL(`${origin}/psq/${id}`)}
          >
            <Text style={styles.link}>Open results on website →</Text>
          </Pressable>
        </ScrollView>
      )}

      <Modal
        visible={kioskVisible}
        animationType="slide"
        presentationStyle="fullScreen"
        onRequestClose={() => {}}
      >
        <View style={styles.kioskContainer}>
          <WebView
            ref={webviewRef}
            source={{ uri: kioskUrl }}
            style={styles.kioskWebview}
            onLoadEnd={() => setKioskLoading(false)}
            onShouldStartLoadWithRequest={(request) =>
              request.url.startsWith(origin)
            }
            javaScriptEnabled
            domStorageEnabled
          />
          {kioskLoading ? (
            <View
              style={[
                styles.kioskLoadingOverlay,
                { backgroundColor: colors.background },
              ]}
            >
              <ActivityIndicator color={colors.primary} size="large" />
            </View>
          ) : null}
          <Pressable
            style={styles.kioskExitBtn}
            onLongPress={confirmExitKiosk}
            delayLongPress={800}
            hitSlop={16}
          >
            <Ionicons name="exit-outline" size={16} color="#ffffff" />
          </Pressable>
        </View>
      </Modal>
    </>
  );
};

const makeStyles = (colors: ColorPalette) =>
  StyleSheet.create({
    content: { padding: spacing.lg, paddingBottom: 48 },
    empty: {
      margin: spacing.lg,
      color: colors.textMuted,
      fontFamily: fonts.regular,
    },
    title: {
      fontFamily: fonts.bold,
      fontSize: 22,
      color: colors.text,
      marginBottom: 4,
    },
    meta: {
      fontFamily: fonts.regular,
      color: colors.textMuted,
      marginBottom: spacing.md,
    },
    heading: {
      fontFamily: fonts.bold,
      fontSize: 18,
      color: colors.text,
      marginBottom: spacing.sm,
      marginTop: spacing.sm,
    },
    card: {
      backgroundColor: colors.surface,
      borderRadius: radii.lg,
      borderWidth: 1,
      borderColor: colors.cardBorder,
      padding: spacing.lg,
      marginBottom: spacing.md,
    },
    cardHeading: {
      fontFamily: fonts.bold,
      fontSize: 16,
      color: colors.text,
      marginBottom: 4,
    },
    cardHeadingRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: spacing.sm,
      marginBottom: 4,
    },
    cardHint: {
      fontFamily: fonts.regular,
      fontSize: 13,
      color: colors.textMuted,
      marginBottom: 12,
      lineHeight: 18,
    },
    cardHintPulsing: {
      fontFamily: fonts.medium,
      fontSize: 13,
      color: colors.primary,
      marginBottom: 12,
      lineHeight: 18,
    },
    summaryBody: {
      fontFamily: fonts.regular,
      fontSize: 14,
      color: colors.text,
      lineHeight: 20,
    },
    label: {
      fontFamily: fonts.bold,
      fontSize: 12,
      color: colors.textMuted,
      textTransform: "uppercase",
      marginBottom: 8,
    },
    subLabel: {
      fontFamily: fonts.bold,
      fontSize: 12,
      color: colors.text,
      textTransform: "uppercase",
      marginTop: spacing.sm,
      marginBottom: 4,
    },
    url: {
      fontFamily: fonts.regular,
      color: colors.text,
      marginBottom: 12,
      fontSize: 13,
    },
    input: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: radii.sm,
      padding: 12,
      marginBottom: 8,
      color: colors.text,
      backgroundColor: colors.background,
      fontFamily: fonts.regular,
      // Web (RN Web) draws its own black focus ring on inputs; zero it out here
      // so the existing border-color focus affordance stays the only indicator.
      // No-op on native.
      outlineWidth: 0,
    },
    questionRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      marginBottom: 4,
    },
    dashedBtn: {
      borderWidth: 1,
      borderStyle: "dashed",
      borderColor: colors.border,
      borderRadius: radii.sm,
      paddingVertical: 10,
      alignItems: "center",
      marginTop: 4,
    },
    dashedBtnText: {
      fontFamily: fonts.semiBold,
      color: colors.textMuted,
      fontSize: 13,
    },
    saving: {
      fontFamily: fonts.regular,
      fontSize: 12,
      color: colors.textMuted,
      textAlign: "center",
      marginTop: 8,
    },
    progressRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-end",
      marginBottom: 8,
    },
    progressCount: {
      fontFamily: fonts.bold,
      fontSize: 36,
      color: colors.primary,
    },
    progressTrack: {
      height: 12,
      borderRadius: 6,
      backgroundColor: colors.border,
      overflow: "hidden",
      marginBottom: 12,
    },
    progressFill: { height: "100%", borderRadius: 6 },
    statusBox: {
      borderRadius: radii.sm,
      padding: spacing.md,
    },
    statusOk: { backgroundColor: colors.successMuted },
    statusLocked: { backgroundColor: "#fffbeb" },
    statusTitle: {
      fontFamily: fonts.bold,
      fontSize: 14,
      color: "#b45309",
      marginBottom: 4,
    },
    statusBody: {
      fontFamily: fonts.regular,
      fontSize: 13,
      color: colors.textMuted,
      lineHeight: 18,
    },
    standardBadge: {
      backgroundColor: colors.primaryMuted,
      borderRadius: radii.sm,
      padding: 10,
      alignSelf: "flex-start",
    },
    standardBadgeText: {
      fontFamily: fonts.bold,
      fontSize: 12,
      color: colors.primary,
    },
    link: {
      color: colors.primary,
      fontFamily: fonts.bold,
      marginTop: 8,
    },
    disabledLink: { opacity: 0.4 },
    danger: {
      color: colors.danger,
      fontFamily: fonts.semiBold,
      marginBottom: 8,
    },
    note: {
      fontFamily: fonts.regular,
      color: colors.textMuted,
      lineHeight: 20,
      marginBottom: 12,
    },
    outlineBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      borderWidth: 1,
      borderColor: colors.primary,
      borderRadius: radii.sm,
      paddingVertical: 10,
      paddingHorizontal: 16,
      alignSelf: "flex-start",
    },
    outlineBtnText: {
      fontFamily: fonts.bold,
      color: colors.primary,
      fontSize: 14,
    },
    outlineBtnSm: {
      borderWidth: 1,
      borderColor: colors.primary,
      borderRadius: radii.sm,
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    outlineBtnSmText: {
      fontFamily: fonts.bold,
      fontSize: 12,
      color: colors.primary,
    },
    btnDisabled: {
      opacity: 0.6,
    },
    kioskCard: {
      gap: spacing.sm,
    },
    kioskCardRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing.sm,
      marginBottom: 4,
    },
    kioskIconCircle: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.primaryMuted,
      alignItems: "center",
      justifyContent: "center",
    },
    kioskCardText: {
      flex: 1,
    },
    qrCard: {
      alignItems: "center",
    },
    qrCaptionRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      marginBottom: spacing.sm,
    },
    qrImageWrap: {
      backgroundColor: "#ffffff",
      padding: spacing.sm,
      borderRadius: radii.sm,
      borderWidth: 1,
      borderColor: colors.cardBorder,
      marginBottom: spacing.sm,
    },
    qrImage: {
      width: 180,
      height: 180,
    },
    qrHint: {
      fontFamily: fonts.regular,
      fontSize: 12,
      color: colors.textMuted,
      marginBottom: spacing.sm,
      textAlign: "center",
    },
    kioskContainer: {
      flex: 1,
      backgroundColor: "#000000",
    },
    kioskWebview: {
      flex: 1,
    },
    kioskLoadingOverlay: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      alignItems: "center",
      justifyContent: "center",
    },
    kioskExitBtn: {
      position: "absolute",
      top: 48,
      right: 16,
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: "rgba(0, 0, 0, 0.35)",
      alignItems: "center",
      justifyContent: "center",
      opacity: 0.35,
    },
    lockedCard: {
      backgroundColor: "#fffbeb",
      borderColor: "#fde68a",
    },
    lockedTitle: {
      fontFamily: fonts.bold,
      fontSize: 16,
      color: "#b45309",
      marginBottom: 4,
    },
    lockedCount: {
      fontFamily: fonts.bold,
      fontSize: 12,
      color: "#b45309",
      textTransform: "uppercase",
    },
    upsellCard: {
      alignItems: "flex-start",
    },
    btn: {
      alignSelf: "flex-end",
      backgroundColor: colors.primary,
      borderRadius: radii.sm,
      paddingHorizontal: 16,
      paddingVertical: 10,
    },
    btnText: { color: "#fff", fontFamily: fonts.bold },
    statRow: {
      flexDirection: "row",
      gap: spacing.sm,
    },
    statTile: {
      flex: 1,
      alignItems: "center",
      backgroundColor: colors.background,
      borderRadius: radii.sm,
      paddingVertical: spacing.sm,
      paddingHorizontal: 6,
      gap: 4,
    },
    statValue: {
      fontFamily: fonts.bold,
      fontSize: 22,
      color: colors.primary,
      textAlign: "center",
    },
    statValueText: {
      fontSize: 13,
      lineHeight: 17,
    },
    statLabel: {
      fontFamily: fonts.regular,
      fontSize: 11,
      color: colors.textMuted,
      textAlign: "center",
    },
    feedbackBlock: {
      backgroundColor: colors.background,
      borderRadius: radii.sm,
      padding: spacing.sm,
      gap: 6,
      marginBottom: spacing.sm,
    },
    feedbackQuestion: {
      fontFamily: fonts.bold,
      fontSize: 11,
      color: colors.textMuted,
      textTransform: "uppercase",
    },
    feedbackAnswer: {
      fontFamily: fonts.regular,
      fontSize: 13,
      color: colors.text,
      lineHeight: 18,
      fontStyle: "italic",
    },
    commentBlockGood: {
      backgroundColor: colors.successMuted,
      borderRadius: radii.sm,
      padding: spacing.sm,
      marginBottom: 6,
    },
    commentBlockImprove: {
      backgroundColor: "#fffbeb",
      borderRadius: radii.sm,
      padding: spacing.sm,
      marginBottom: 6,
    },
    commentText: {
      fontFamily: fonts.regular,
      fontSize: 13,
      color: colors.text,
      lineHeight: 18,
      fontStyle: "italic",
    },
    emptyComment: {
      fontFamily: fonts.regular,
      fontSize: 13,
      color: colors.textMuted,
      fontStyle: "italic",
      marginBottom: 6,
    },
    outlineBtnFull: {
      borderWidth: 1,
      borderColor: colors.primary,
      borderRadius: radii.sm,
      paddingVertical: 10,
      alignItems: "center",
      marginBottom: spacing.sm,
    },
    outlineBtnFullText: {
      fontFamily: fonts.bold,
      fontSize: 14,
      color: colors.primary,
    },
    aiLoading: {
      alignItems: "center",
      gap: 8,
      paddingVertical: spacing.md,
    },
    reflectionInput: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: radii.sm,
      padding: 12,
      minHeight: 200,
      backgroundColor: colors.background,
      color: colors.text,
      fontFamily: fonts.regular,
      fontSize: 14,
      lineHeight: 21,
      marginBottom: spacing.sm,
      outlineWidth: 0,
    },
    reflectionActions: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
  });

export default PsqDetailScreen;
